version: 2

jobs:
  build:
    orbs:
      maven: circleci/maven@1.2.0
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/openjdk:8u181-jdk
    branches:
      only: master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: | 
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          command: | 
            mvn clean install -Dmaven.test.skip=true