version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/mysql:8.0
      - image: circleci/maven@3.6.3
       auth:
          username: 451573589
          password: yuanfen.123
    steps:
      - checkout
      - run:
          command: maven install
      
