version: 2

jobs:
  build:
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
        aws_auth:
          aws_access_key_id: "AKIA4NCY7GAEKEBUVUUN" 
          aws_secret_access_key: "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"
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/mysql:8.0
    orbs:
      maven: circleci/maven@1.2.0
    steps:
      - checkout
      - run:
          command: 
            mvn install
