version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/mysql:8.0
    orbs:
      maven: circleci/maven@1.2.0
    steps:
      - checkout
      - run:
          command: 
            mvn install
