version: 2

jobs:
  build:
    docker:
      - image: 852737601544.dkr.ecr.us-east-1.amazonaws.com:0.1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID 
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/mysql:8.0
    orbs:
      maven: circleci/maven@1.2.0
    steps:
      - checkout
      - run:
          command: 
            mvn install
    machine:
    pre:
      - sudo curl -L -o /usr/bin/docker 'https://s3-external-1.amazonaws.com/circle-downloads/docker-1.9.0-circleci'
      - sudo chmod 0755 /usr/bin/docker
    services:
          - docker
    deployment:
      prod:
        branch: master
        commands:
          - ./deploy.sh