version: 2

machine:
  python:
    version: 3.7.9

jobs:
  build:
    working_directory: /studyMama
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/python
    orbs:
      maven: circleci/maven@1.2.0
    branches:
      only: master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apt-get install python3-pip python3-venv
            ptyhon3 -m venv -venv
            source venv/bin/activate
            pip3 install docker-compose
      - run:
          command: 
            mvn clean install -Dmaven.test.skip=true