version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    orbs:
      maven: circleci/maven@1.2.0
    steps:
      - checkout
      - run:
          command: 
            mvn clean install -Dmaven.test.skip=true