version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
  deploy:
    machine: true
    steps:
      - checkout
      - run: 
          command: | 
            mvn clean install -Dmaven.test.skip=true
      - run:
          name: docker-compose and run
          command: | 
            echo y | docker image prune
            echo y | docker container prune
            docker-compose -f docker-compose.yml up --build -d
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u "451573589" -p "yuanfen.123"
            docker tag studaymama_test 451573589/studaymama_test:$CIRCLE_SHA1
            docker tag studaymama_test 451573589/studaymama_test:latest
            docker push 451573589/studaymama_test:$CIRCLE_SHA1
            docker push 451573589/studaymama_test:latest
          
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build 
            - deploy:
                requires:
                  - build
                filters:
                    branches:
                        only:
                          - master