version: 2

jobs:
  build:
    working_directory: /studyMama
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
  deploy:
    working_directory: /studyMama
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: | 
            cd /studyMama
            mvn clean install -Dmaven.test.skip=true
          
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build 
            - deploy:
                requires:
                  - build
                filters:
                    branches:
                        only:
                          - master